# security check action script

name: terraform-security-check
on: [pull_request,push]

jobs:
  tfsec:
    name: server name
    runs-on: ubuntu-latest

    steps:
      - name: clone repository to vertual environment
        uses: actions/checkout@master

      - name: tfsec commentor
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          github_token: ${{ github.token }}
      - name: tf security scan
        uses: triat/terraform-security-scan@v2.0.2
      - name: terraform fmt
        uses: dflook/terraform-fmt@v1
      - name: Lint Terraform
        uses: actionshub/terraform-lint@main




